export enum Role {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum UserStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum EventLevel {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ALERT = 'ALERT',
  FINANCE = 'FINANCE',
}

export enum ShiftStatus {
  NEW = 'NEW',
  OPEN = 'OPEN',
  WAITING_OWNER_CONFIRMATION = 'WAITING_OWNER_CONFIRMATION',
  ASSIGNED = 'ASSIGNED',
  STARTED = 'STARTED',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ShiftResponseType {
  TAKE = 'TAKE',
  DECLINE = 'DECLINE',
}

export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_APPROVED = 'USER_APPROVED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  BOT_STARTED = 'BOT_STARTED',
  BOT_ERROR = 'BOT_ERROR',
  SHIFT_CREATED = 'SHIFT_CREATED',
  SHIFT_RESPONSE_CREATED = 'SHIFT_RESPONSE_CREATED',
  SHIFT_ASSIGNED = 'SHIFT_ASSIGNED',
}
