export enum Role {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum UserStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum EventLevel {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ALERT = 'ALERT',
  FINANCE = 'FINANCE',
}

export enum ShiftStatus {
  NEW = 'NEW',
  OPEN = 'OPEN',
  WAITING_OWNER_CONFIRMATION = 'WAITING_OWNER_CONFIRMATION',
  ASSIGNED = 'ASSIGNED',
  STARTED = 'STARTED',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ShiftResponseType {
  TAKE = 'TAKE',
  DECLINE = 'DECLINE',
}

export enum ShiftPhotoType {
  START = 'START',
  READY = 'READY',
  END = 'END',
}

export enum IncidentCategory {
  EQUIPMENT = 'EQUIPMENT',
  CLIENT = 'CLIENT',
  CLEANING = 'CLEANING',
  SAFETY = 'SAFETY',
  SUPPLY = 'SUPPLY',
  OTHER = 'OTHER',
}

export enum IncidentStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
}

export enum TaskStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_CONFIRMATION = 'WAITING_CONFIRMATION',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED',
}

export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_APPROVED = 'USER_APPROVED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  BOT_STARTED = 'BOT_STARTED',
  BOT_ERROR = 'BOT_ERROR',
  SHIFT_CREATED = 'SHIFT_CREATED',
  SHIFT_RESPONSE_CREATED = 'SHIFT_RESPONSE_CREATED',
  SHIFT_ASSIGNED = 'SHIFT_ASSIGNED',
  SHIFT_STARTED = 'SHIFT_STARTED',
  SHIFT_READY = 'SHIFT_READY',
  SHIFT_COMPLETED = 'SHIFT_COMPLETED',
  SHIFT_PHOTO_ADDED = 'SHIFT_PHOTO_ADDED',
  SHIFT_REPORT_CREATED = 'SHIFT_REPORT_CREATED',
  SHIFT_CLOSED = 'SHIFT_CLOSED',
  PAYROLL_CREATED = 'PAYROLL_CREATED',
  PAYMENT_MARKED = 'PAYMENT_MARKED',
  INCIDENT_CREATED = 'INCIDENT_CREATED',
  INCIDENT_RESOLVED = 'INCIDENT_RESOLVED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_STARTED = 'TASK_STARTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_CONFIRMED = 'TASK_CONFIRMED',
  TASK_CANCELLED = 'TASK_CANCELLED',
}
