export enum Role {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum UserStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum EventLevel {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ALERT = 'ALERT',
  FINANCE = 'FINANCE',
}

export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_APPROVED = 'USER_APPROVED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  BOT_STARTED = 'BOT_STARTED',
  BOT_ERROR = 'BOT_ERROR',
}
